<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>org.qatlas</groupId>
    <artifactId>qatlas-backend</artifactId>
    <version>1.0.0</version><!--Please update "swagger.client.app.version" property also to the same as this-->
    <name>QAtlas Backend</name>
    <description>REST API and reporting backend for QAtlas, an open-source test execution reporting tool</description>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
        <java.version>21</java.version>
        <commons.collections4.version>4.4</commons.collections4.version>
        <commons.beanutils.version>1.9.4</commons.beanutils.version>
        <commons.validator.version>1.9.0</commons.validator.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <swagger.codegen.version>3.0.25</swagger.codegen.version>
        <commons.codec.version>1.17.1</commons.codec.version>
        <swagger.client.app.version>1.0.0</swagger.client.app.version>
        <springdoc.openapi.version>3.1.0</springdoc.openapi.version>
        <mysql.connector.version>9.1.0</mysql.connector.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.connector.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc.openapi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>${commons.collections4.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>${commons.beanutils.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>${commons.validator.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>${commons.codec.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- config properties processor -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>-Xmx1024m</jvmArguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>api-client-gen</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.swagger.codegen.v3</groupId>
                        <artifactId>swagger-codegen-maven-plugin</artifactId>
                        <version>${swagger.codegen.version}</version>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <inputSpec>http://localhost:8080/v3/api-docs</inputSpec>
                                    <language>java</language>
                                    <output>${project.build.directory}/openapi-client-generated</output>
                                    <addCompileSourceRoot>false</addCompileSourceRoot>
                                    <templateDirectory>src/main/resources/codegen-templates</templateDirectory>
                                    <groupId>org.qatlas</groupId>
                                    <artifactId>qatlas-client</artifactId>
                                    <artifactVersion>${swagger.client.app.version}</artifactVersion>
                                    <apiPackage>org.qatlas.client.handler</apiPackage>
                                    <modelPackage>org.qatlas.client.model</modelPackage>
                                    <invokerPackage>org.qatlas.client.handler</invokerPackage>
                                    <configOptions>
                                        <dateLibrary>java8-localdatetime</dateLibrary>
                                        <artifactUrl>https://qatlas.org</artifactUrl>
                                        <artifactDescription>REST client library for the QAtlas test reporting API</artifactDescription>
                                        <scmConnection>scm:git:git://github.com/qatlas/qatlas-reporting.git</scmConnection>
                                        <scmDeveloperConnection>scm:git:ssh://github.com:qatlas/qatlas-reporting.git</scmDeveloperConnection>
                                        <scmUrl>https://github.com/qatlas/qatlas-reporting/tree/qatlas-client-maven-repo</scmUrl>
                                        <developerName>QAtlas</developerName>
                                        <developerEmail>hello@qatlas.org</developerEmail>
                                        <developerOrganization>QAtlas</developerOrganization>
                                        <developerOrganizationUrl>https://qatlas.org</developerOrganizationUrl>
                                    </configOptions>
                                    <library>resttemplate</library>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>prod</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <excludes>
                            <exclude>**/classic/**</exclude>
                            <exclude>/codegen-templates/**</exclude>
                            <exclude>/META-INF/**</exclude>
                        </excludes>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>

</project>
