/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.handler;

import org.qatlas.client.model.Application;
import org.qatlas.client.model.TestExecution;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationApi
 */
@Ignore
public class ApplicationApiTest {

    private final ApplicationApi api = new ApplicationApi();

    /**
     * Create an application
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createApplicationTest() {
        Application body = null;
        Application response = api.createApplication(body);

        // TODO: test validations
    }
    /**
     * Delete an application
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteApplicationTest() {
        Long id = null;
        api.deleteApplication(id);

        // TODO: test validations
    }
    /**
     * List all the applications
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllApplicationsTest() {
        List<Application> response = api.getAllApplications();

        // TODO: test validations
    }
    /**
     * Get an application by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApplicationByIdTest() {
        Long id = null;
        Application response = api.getApplicationById(id);

        // TODO: test validations
    }
    /**
     * Get list of test executions of an application
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestExecutionsTest() {
        Long applicationId = null;
        List<TestExecution> response = api.getTestExecutions(applicationId);

        // TODO: test validations
    }
    /**
     * Update an application
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateApplicationTest() {
        Application body = null;
        Application response = api.updateApplication(body);

        // TODO: test validations
    }
}
