/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.handler;

import org.qatlas.client.model.Environment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnvironmentApi
 */
@Ignore
public class EnvironmentApiTest {

    private final EnvironmentApi api = new EnvironmentApi();

    /**
     * Create an environment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEnvironmentTest() {
        Environment body = null;
        Environment response = api.createEnvironment(body);

        // TODO: test validations
    }
    /**
     * Delete an environment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteEnvironmentTest() {
        Long id = null;
        api.deleteEnvironment(id);

        // TODO: test validations
    }
    /**
     * List all environments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllEnvironmentsTest() {
        List<Environment> response = api.getAllEnvironments();

        // TODO: test validations
    }
    /**
     * Get an environment by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEnvironmentByIdTest() {
        Long id = null;
        Environment response = api.getEnvironmentById(id);

        // TODO: test validations
    }
    /**
     * Update an environment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateEnvironmentTest() {
        Environment body = null;
        Environment response = api.updateEnvironment(body);

        // TODO: test validations
    }
}
