/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.handler;

import org.qatlas.client.model.ExecutionStatus;
import org.qatlas.client.model.TestCase;
import org.qatlas.client.model.TestSuite;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestSuiteApi
 */
@Ignore
public class TestSuiteApiTest {

    private final TestSuiteApi api = new TestSuiteApi();

    /**
     * Create a test suite
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTestSuiteTest() {
        TestSuite body = null;
        TestSuite response = api.createTestSuite(body);

        // TODO: test validations
    }
    /**
     * Get list of test suites
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTestSuitesTest() {
        List<TestSuite> response = api.getAllTestSuites();

        // TODO: test validations
    }
    /**
     * Get a test suites by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestSuiteByIdTest() {
        Long id = null;
        TestSuite response = api.getTestSuiteById(id);

        // TODO: test validations
    }
    /**
     * Get list of test cases of a test suite filtered by execution status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestSuiteTestCasesTest() {
        Long testSuiteId = null;
        List<ExecutionStatus> status = null;
        List<TestCase> response = api.getTestSuiteTestCases(testSuiteId, status);

        // TODO: test validations
    }
    /**
     * Update a test suite
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestSuiteTest() {
        TestSuite body = null;
        TestSuite response = api.updateTestSuite(body);

        // TODO: test validations
    }
}
