/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.handler;

import org.qatlas.client.model.TestStep;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestStepApi
 */
@Ignore
public class TestStepApiTest {

    private final TestStepApi api = new TestStepApi();

    /**
     * Create a test step
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTestStepTest() {
        TestStep body = null;
        TestStep response = api.createTestStep(body);

        // TODO: test validations
    }
    /**
     * Get list of all test steps
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTestStepsTest() {
        List<TestStep> response = api.getAllTestSteps();

        // TODO: test validations
    }
    /**
     * Get test step by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestStepByIdTest() {
        Long id = null;
        TestStep response = api.getTestStepById(id);

        // TODO: test validations
    }
}
