/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.handler;

import org.qatlas.client.model.ExecutionStatus;
import java.time.LocalDateTime;
import org.qatlas.client.model.StreamingResponseBody;
import org.qatlas.client.model.TestCase;
import org.qatlas.client.model.TestExecution;
import org.qatlas.client.model.TestSuite;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestExecutionApi
 */
@Ignore
public class TestExecutionApiTest {

    private final TestExecutionApi api = new TestExecutionApi();

    /**
     * Archives the test execution(s)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void archiveTestExecutionTest() {
        List<Long> body = null;
        Boolean deleteAttachmentsOnly = null;
        api.archiveTestExecution(body, deleteAttachmentsOnly);

        // TODO: test validations
    }
    /**
     * Create a test execution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTestExecutionTest() {
        TestExecution body = null;
        TestExecution response = api.createTestExecution(body);

        // TODO: test validations
    }
    /**
     * Download Test Step Attachment(s) of test execution(s)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void downloadAttachmentsTest() {
        List<Long> executionId = null;
        StreamingResponseBody response = api.downloadAttachments(executionId);

        // TODO: test validations
    }
    /**
     * Get list of all test executions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTestExecutionsTest() {
        List<TestExecution> response = api.getAllTestExecutions();

        // TODO: test validations
    }
    /**
     * Get a test execution by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestExecutionByIdTest() {
        Long id = null;
        TestExecution response = api.getTestExecutionById(id);

        // TODO: test validations
    }
    /**
     * Get list of test cases of a test execution filtered by execution status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestExecutionTestCasesTest() {
        Long testExecutionId = null;
        List<ExecutionStatus> status = null;
        List<TestCase> response = api.getTestExecutionTestCases(testExecutionId, status);

        // TODO: test validations
    }
    /**
     * Get list of all test suites of an execution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestSuitesTest() {
        Long executionId = null;
        List<TestSuite> response = api.getTestSuites(executionId);

        // TODO: test validations
    }
    /**
     * Update a test execution end time
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestExecutionEndTimeTest() {
        LocalDateTime body = null;
        Long id = null;
        TestExecution response = api.updateTestExecutionEndTime(body, id);

        // TODO: test validations
    }
}
