/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.handler;

import org.qatlas.client.model.ExecutionStatus;
import java.time.LocalDateTime;
import org.qatlas.client.model.TestCase;
import org.qatlas.client.model.TestStep;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestCaseApi
 */
@Ignore
public class TestCaseApiTest {

    private final TestCaseApi api = new TestCaseApi();

    /**
     * Create a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTestCaseTest() {
        TestCase body = null;
        TestCase response = api.createTestCase(body);

        // TODO: test validations
    }
    /**
     * Get comments of a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentsTest() {
        Long id = null;
        String response = api.getComments(id);

        // TODO: test validations
    }
    /**
     * Get a test cases by it&#x27;s ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestCaseByIdTest() {
        Long id = null;
        TestCase response = api.getTestCaseById(id);

        // TODO: test validations
    }
    /**
     * Get the list of Test Steps of a Test Case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestCaseTestStepsTest() {
        Long testCaseId = null;
        List<TestStep> response = api.getTestCaseTestSteps(testCaseId);

        // TODO: test validations
    }
    /**
     * Get list of all Test Cases
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestCasesTest() {
        List<TestCase> response = api.getTestCases();

        // TODO: test validations
    }
    /**
     * Update comments of a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCommentsTest() {
        String body = null;
        Long id = null;
        String response = api.updateComments(body, id);

        // TODO: test validations
    }
    /**
     * Update a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestCaseTest() {
        TestCase body = null;
        TestCase response = api.updateTestCase(body);

        // TODO: test validations
    }
    /**
     * Update execution status of a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestCaseStatusTest() {
        Long id = null;
        ExecutionStatus executionStatus = null;
        TestCase response = api.updateTestCaseStatus(id, executionStatus);

        // TODO: test validations
    }
    /**
     * Update execution status and end time of a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestCaseStatusAndExecutionEndTimeTest() {
        Long id = null;
        ExecutionStatus executionStatus = null;
        LocalDateTime executionEndTime = null;
        TestCase response = api.updateTestCaseStatusAndExecutionEndTime(id, executionStatus, executionEndTime);

        // TODO: test validations
    }
    /**
     * Update execution status and start time of a test case
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestCaseStatusAndStartTimeTest() {
        Long id = null;
        ExecutionStatus executionStatus = null;
        LocalDateTime executionStartTime = null;
        TestCase response = api.updateTestCaseStatusAndStartTime(id, executionStatus, executionStartTime);

        // TODO: test validations
    }
}
