/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AttachmentType = 'SNAPSHOT' | 'OTHER';

export const AttachmentType = {
    SNAPSHOT: 'SNAPSHOT' as AttachmentType,
    OTHER: 'OTHER' as AttachmentType
};