/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ExecutionStatus = 'PROGRESS' | 'PASSED' | 'FAILED' | 'WARNING';

export const ExecutionStatus = {
    PROGRESS: 'PROGRESS' as ExecutionStatus,
    PASSED: 'PASSED' as ExecutionStatus,
    FAILED: 'FAILED' as ExecutionStatus,
    WARNING: 'WARNING' as ExecutionStatus
};