/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TestExecution { 
    id: number;
    name: string;
    applicationId: number;
    readonly applicationName?: string;
    applicationVersion?: string;
    environmentId: number;
    readonly environmentName?: string;
    browser: string;
    operatingSystem?: string;
    systemIp: string;
    systemName: string;
    executedBy?: string;
    startTime: Date;
    endTime?: Date;
    readonly targetedTestCaseCount?: number;
    readonly executedTestCaseCount?: number;
    readonly passedTestCaseCount?: number;
    readonly failedTestCaseCount?: number;
    readonly skippedTestCaseCount?: number;
    readonly inProgressTestCaseCount?: number;
}