/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AttachmentType } from './attachmentType';


export interface TestStepAttachment { 
    id?: number;
    testStepId?: number;
    attachmentType: AttachmentType;
    fileName: string;
    fileContent: string;
    fileContentBase64Encoded?: boolean;
    readonly attachmentRelativePath?: string;
}