/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ExecutionStatus } from './executionStatus';
import { TestStep } from './testStep';


export interface TestCase { 
    id: number;
    testSuiteId: number;
    readonly testSuiteName?: string;
    name: string;
    executionStatus: ExecutionStatus;
    executionStartTime: Date;
    executionEndTime?: Date;
    readonly testSteps?: Array<TestStep>;
    readonly executionTime?: number;
    readonly totalTestStepCount?: number;
    readonly executedTestStepCount?: number;
    readonly passedTestStepCount?: number;
    readonly failedTestStepCount?: number;
    readonly testStepCountWithWarnings?: number;
}