/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ExecutionStatus
 */
public enum ExecutionStatus {
  PLANNED("PLANNED"),
  PROGRESS("PROGRESS"),
  PASSED("PASSED"),
  FAILED("FAILED"),
  WARNING("WARNING");

  private String value;

  ExecutionStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ExecutionStatus fromValue(String text) {
    for (ExecutionStatus b : ExecutionStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
