/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
/**
 * TestExecution
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-02T18:40:14.833+02:00[Europe/Berlin]")
public class TestExecution {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("applicationId")
  private Long applicationId = null;

  @JsonProperty("applicationName")
  private String applicationName = null;

  @JsonProperty("applicationVersion")
  private String applicationVersion = null;

  @JsonProperty("environmentId")
  private Long environmentId = null;

  @JsonProperty("environmentName")
  private String environmentName = null;

  @JsonProperty("browser")
  private String browser = null;

  @JsonProperty("operatingSystem")
  private String operatingSystem = null;

  @JsonProperty("systemIp")
  private String systemIp = null;

  @JsonProperty("systemName")
  private String systemName = null;

  @JsonProperty("executedBy")
  private String executedBy = null;

  @JsonProperty("startTime")
  private LocalDateTime startTime = null;

  @JsonProperty("endTime")
  private LocalDateTime endTime = null;

  @JsonProperty("archived")
  private Boolean archived = null;

  @JsonProperty("targetedTestCaseCount")
  private Integer targetedTestCaseCount = null;

  @JsonProperty("failedTestCaseCount")
  private Integer failedTestCaseCount = null;

  @JsonProperty("executedTestCaseCount")
  private Integer executedTestCaseCount = null;

  @JsonProperty("skippedTestCaseCount")
  private Integer skippedTestCaseCount = null;

  @JsonProperty("inProgressTestCaseCount")
  private Integer inProgressTestCaseCount = null;

  @JsonProperty("passedTestCaseCount")
  private Integer passedTestCaseCount = null;

  public TestExecution id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestExecution name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestExecution applicationId(Long applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @Schema(required = true, description = "")
  public Long getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Long applicationId) {
    this.applicationId = applicationId;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @Schema(description = "")
  public String getApplicationName() {
    return applicationName;
  }

  public TestExecution applicationVersion(String applicationVersion) {
    this.applicationVersion = applicationVersion;
    return this;
  }

   /**
   * Get applicationVersion
   * @return applicationVersion
  **/
  @Schema(description = "")
  public String getApplicationVersion() {
    return applicationVersion;
  }

  public void setApplicationVersion(String applicationVersion) {
    this.applicationVersion = applicationVersion;
  }

  public TestExecution environmentId(Long environmentId) {
    this.environmentId = environmentId;
    return this;
  }

   /**
   * Get environmentId
   * @return environmentId
  **/
  @Schema(required = true, description = "")
  public Long getEnvironmentId() {
    return environmentId;
  }

  public void setEnvironmentId(Long environmentId) {
    this.environmentId = environmentId;
  }

   /**
   * Get environmentName
   * @return environmentName
  **/
  @Schema(description = "")
  public String getEnvironmentName() {
    return environmentName;
  }

  public TestExecution browser(String browser) {
    this.browser = browser;
    return this;
  }

   /**
   * Get browser
   * @return browser
  **/
  @Schema(required = true, description = "")
  public String getBrowser() {
    return browser;
  }

  public void setBrowser(String browser) {
    this.browser = browser;
  }

  public TestExecution operatingSystem(String operatingSystem) {
    this.operatingSystem = operatingSystem;
    return this;
  }

   /**
   * Get operatingSystem
   * @return operatingSystem
  **/
  @Schema(description = "")
  public String getOperatingSystem() {
    return operatingSystem;
  }

  public void setOperatingSystem(String operatingSystem) {
    this.operatingSystem = operatingSystem;
  }

  public TestExecution systemIp(String systemIp) {
    this.systemIp = systemIp;
    return this;
  }

   /**
   * Get systemIp
   * @return systemIp
  **/
  @Schema(required = true, description = "")
  public String getSystemIp() {
    return systemIp;
  }

  public void setSystemIp(String systemIp) {
    this.systemIp = systemIp;
  }

  public TestExecution systemName(String systemName) {
    this.systemName = systemName;
    return this;
  }

   /**
   * Get systemName
   * @return systemName
  **/
  @Schema(required = true, description = "")
  public String getSystemName() {
    return systemName;
  }

  public void setSystemName(String systemName) {
    this.systemName = systemName;
  }

  public TestExecution executedBy(String executedBy) {
    this.executedBy = executedBy;
    return this;
  }

   /**
   * Get executedBy
   * @return executedBy
  **/
  @Schema(description = "")
  public String getExecutedBy() {
    return executedBy;
  }

  public void setExecutedBy(String executedBy) {
    this.executedBy = executedBy;
  }

  public TestExecution startTime(LocalDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @Schema(required = true, description = "")
  public LocalDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(LocalDateTime startTime) {
    this.startTime = startTime;
  }

  public TestExecution endTime(LocalDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @Schema(description = "")
  public LocalDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(LocalDateTime endTime) {
    this.endTime = endTime;
  }

  public TestExecution archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  @Schema(description = "")
  public Boolean isArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

   /**
   * Get targetedTestCaseCount
   * @return targetedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getTargetedTestCaseCount() {
    return targetedTestCaseCount;
  }

   /**
   * Get failedTestCaseCount
   * @return failedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getFailedTestCaseCount() {
    return failedTestCaseCount;
  }

   /**
   * Get executedTestCaseCount
   * @return executedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getExecutedTestCaseCount() {
    return executedTestCaseCount;
  }

   /**
   * Get skippedTestCaseCount
   * @return skippedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getSkippedTestCaseCount() {
    return skippedTestCaseCount;
  }

   /**
   * Get inProgressTestCaseCount
   * @return inProgressTestCaseCount
  **/
  @Schema(description = "")
  public Integer getInProgressTestCaseCount() {
    return inProgressTestCaseCount;
  }

   /**
   * Get passedTestCaseCount
   * @return passedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getPassedTestCaseCount() {
    return passedTestCaseCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestExecution testExecution = (TestExecution) o;
    return Objects.equals(this.id, testExecution.id) &&
        Objects.equals(this.name, testExecution.name) &&
        Objects.equals(this.applicationId, testExecution.applicationId) &&
        Objects.equals(this.applicationName, testExecution.applicationName) &&
        Objects.equals(this.applicationVersion, testExecution.applicationVersion) &&
        Objects.equals(this.environmentId, testExecution.environmentId) &&
        Objects.equals(this.environmentName, testExecution.environmentName) &&
        Objects.equals(this.browser, testExecution.browser) &&
        Objects.equals(this.operatingSystem, testExecution.operatingSystem) &&
        Objects.equals(this.systemIp, testExecution.systemIp) &&
        Objects.equals(this.systemName, testExecution.systemName) &&
        Objects.equals(this.executedBy, testExecution.executedBy) &&
        Objects.equals(this.startTime, testExecution.startTime) &&
        Objects.equals(this.endTime, testExecution.endTime) &&
        Objects.equals(this.archived, testExecution.archived) &&
        Objects.equals(this.targetedTestCaseCount, testExecution.targetedTestCaseCount) &&
        Objects.equals(this.failedTestCaseCount, testExecution.failedTestCaseCount) &&
        Objects.equals(this.executedTestCaseCount, testExecution.executedTestCaseCount) &&
        Objects.equals(this.skippedTestCaseCount, testExecution.skippedTestCaseCount) &&
        Objects.equals(this.inProgressTestCaseCount, testExecution.inProgressTestCaseCount) &&
        Objects.equals(this.passedTestCaseCount, testExecution.passedTestCaseCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, applicationId, applicationName, applicationVersion, environmentId, environmentName, browser, operatingSystem, systemIp, systemName, executedBy, startTime, endTime, archived, targetedTestCaseCount, failedTestCaseCount, executedTestCaseCount, skippedTestCaseCount, inProgressTestCaseCount, passedTestCaseCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestExecution {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    applicationVersion: ").append(toIndentedString(applicationVersion)).append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    environmentName: ").append(toIndentedString(environmentName)).append("\n");
    sb.append("    browser: ").append(toIndentedString(browser)).append("\n");
    sb.append("    operatingSystem: ").append(toIndentedString(operatingSystem)).append("\n");
    sb.append("    systemIp: ").append(toIndentedString(systemIp)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("    executedBy: ").append(toIndentedString(executedBy)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    targetedTestCaseCount: ").append(toIndentedString(targetedTestCaseCount)).append("\n");
    sb.append("    failedTestCaseCount: ").append(toIndentedString(failedTestCaseCount)).append("\n");
    sb.append("    executedTestCaseCount: ").append(toIndentedString(executedTestCaseCount)).append("\n");
    sb.append("    skippedTestCaseCount: ").append(toIndentedString(skippedTestCaseCount)).append("\n");
    sb.append("    inProgressTestCaseCount: ").append(toIndentedString(inProgressTestCaseCount)).append("\n");
    sb.append("    passedTestCaseCount: ").append(toIndentedString(passedTestCaseCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
