/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
/**
 * TestSuite
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-02T18:40:14.833+02:00[Europe/Berlin]")
public class TestSuite {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("testExecutionId")
  private Long testExecutionId = null;

  @JsonProperty("testExecutionName")
  private String testExecutionName = null;

  @JsonProperty("testSuiteName")
  private String testSuiteName = null;

  @JsonProperty("executionStartTime")
  private LocalDateTime executionStartTime = null;

  @JsonProperty("executionEndTime")
  private LocalDateTime executionEndTime = null;

  @JsonProperty("plannedTestCaseCount")
  private Integer plannedTestCaseCount = null;

  @JsonProperty("testCasesCountWithWarnings")
  private Integer testCasesCountWithWarnings = null;

  @JsonProperty("failedTestCaseCount")
  private Integer failedTestCaseCount = null;

  @JsonProperty("executedTestCaseCount")
  private Integer executedTestCaseCount = null;

  @JsonProperty("skippedTestCaseCount")
  private Integer skippedTestCaseCount = null;

  @JsonProperty("inProgressTestCaseCount")
  private Integer inProgressTestCaseCount = null;

  @JsonProperty("passedTestCaseCount")
  private Integer passedTestCaseCount = null;

  public TestSuite id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestSuite testExecutionId(Long testExecutionId) {
    this.testExecutionId = testExecutionId;
    return this;
  }

   /**
   * Get testExecutionId
   * @return testExecutionId
  **/
  @Schema(required = true, description = "")
  public Long getTestExecutionId() {
    return testExecutionId;
  }

  public void setTestExecutionId(Long testExecutionId) {
    this.testExecutionId = testExecutionId;
  }

   /**
   * Get testExecutionName
   * @return testExecutionName
  **/
  @Schema(description = "")
  public String getTestExecutionName() {
    return testExecutionName;
  }

  public TestSuite testSuiteName(String testSuiteName) {
    this.testSuiteName = testSuiteName;
    return this;
  }

   /**
   * Get testSuiteName
   * @return testSuiteName
  **/
  @Schema(required = true, description = "")
  public String getTestSuiteName() {
    return testSuiteName;
  }

  public void setTestSuiteName(String testSuiteName) {
    this.testSuiteName = testSuiteName;
  }

  public TestSuite executionStartTime(LocalDateTime executionStartTime) {
    this.executionStartTime = executionStartTime;
    return this;
  }

   /**
   * Get executionStartTime
   * @return executionStartTime
  **/
  @Schema(required = true, description = "")
  public LocalDateTime getExecutionStartTime() {
    return executionStartTime;
  }

  public void setExecutionStartTime(LocalDateTime executionStartTime) {
    this.executionStartTime = executionStartTime;
  }

  public TestSuite executionEndTime(LocalDateTime executionEndTime) {
    this.executionEndTime = executionEndTime;
    return this;
  }

   /**
   * Get executionEndTime
   * @return executionEndTime
  **/
  @Schema(description = "")
  public LocalDateTime getExecutionEndTime() {
    return executionEndTime;
  }

  public void setExecutionEndTime(LocalDateTime executionEndTime) {
    this.executionEndTime = executionEndTime;
  }

  public TestSuite plannedTestCaseCount(Integer plannedTestCaseCount) {
    this.plannedTestCaseCount = plannedTestCaseCount;
    return this;
  }

   /**
   * Get plannedTestCaseCount
   * @return plannedTestCaseCount
  **/
  @Schema(required = true, description = "")
  public Integer getPlannedTestCaseCount() {
    return plannedTestCaseCount;
  }

  public void setPlannedTestCaseCount(Integer plannedTestCaseCount) {
    this.plannedTestCaseCount = plannedTestCaseCount;
  }

   /**
   * Get testCasesCountWithWarnings
   * @return testCasesCountWithWarnings
  **/
  @Schema(description = "")
  public Integer getTestCasesCountWithWarnings() {
    return testCasesCountWithWarnings;
  }

   /**
   * Get failedTestCaseCount
   * @return failedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getFailedTestCaseCount() {
    return failedTestCaseCount;
  }

   /**
   * Get executedTestCaseCount
   * @return executedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getExecutedTestCaseCount() {
    return executedTestCaseCount;
  }

   /**
   * Get skippedTestCaseCount
   * @return skippedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getSkippedTestCaseCount() {
    return skippedTestCaseCount;
  }

   /**
   * Get inProgressTestCaseCount
   * @return inProgressTestCaseCount
  **/
  @Schema(description = "")
  public Integer getInProgressTestCaseCount() {
    return inProgressTestCaseCount;
  }

   /**
   * Get passedTestCaseCount
   * @return passedTestCaseCount
  **/
  @Schema(description = "")
  public Integer getPassedTestCaseCount() {
    return passedTestCaseCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestSuite testSuite = (TestSuite) o;
    return Objects.equals(this.id, testSuite.id) &&
        Objects.equals(this.testExecutionId, testSuite.testExecutionId) &&
        Objects.equals(this.testExecutionName, testSuite.testExecutionName) &&
        Objects.equals(this.testSuiteName, testSuite.testSuiteName) &&
        Objects.equals(this.executionStartTime, testSuite.executionStartTime) &&
        Objects.equals(this.executionEndTime, testSuite.executionEndTime) &&
        Objects.equals(this.plannedTestCaseCount, testSuite.plannedTestCaseCount) &&
        Objects.equals(this.testCasesCountWithWarnings, testSuite.testCasesCountWithWarnings) &&
        Objects.equals(this.failedTestCaseCount, testSuite.failedTestCaseCount) &&
        Objects.equals(this.executedTestCaseCount, testSuite.executedTestCaseCount) &&
        Objects.equals(this.skippedTestCaseCount, testSuite.skippedTestCaseCount) &&
        Objects.equals(this.inProgressTestCaseCount, testSuite.inProgressTestCaseCount) &&
        Objects.equals(this.passedTestCaseCount, testSuite.passedTestCaseCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, testExecutionId, testExecutionName, testSuiteName, executionStartTime, executionEndTime, plannedTestCaseCount, testCasesCountWithWarnings, failedTestCaseCount, executedTestCaseCount, skippedTestCaseCount, inProgressTestCaseCount, passedTestCaseCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestSuite {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    testExecutionId: ").append(toIndentedString(testExecutionId)).append("\n");
    sb.append("    testExecutionName: ").append(toIndentedString(testExecutionName)).append("\n");
    sb.append("    testSuiteName: ").append(toIndentedString(testSuiteName)).append("\n");
    sb.append("    executionStartTime: ").append(toIndentedString(executionStartTime)).append("\n");
    sb.append("    executionEndTime: ").append(toIndentedString(executionEndTime)).append("\n");
    sb.append("    plannedTestCaseCount: ").append(toIndentedString(plannedTestCaseCount)).append("\n");
    sb.append("    testCasesCountWithWarnings: ").append(toIndentedString(testCasesCountWithWarnings)).append("\n");
    sb.append("    failedTestCaseCount: ").append(toIndentedString(failedTestCaseCount)).append("\n");
    sb.append("    executedTestCaseCount: ").append(toIndentedString(executedTestCaseCount)).append("\n");
    sb.append("    skippedTestCaseCount: ").append(toIndentedString(skippedTestCaseCount)).append("\n");
    sb.append("    inProgressTestCaseCount: ").append(toIndentedString(inProgressTestCaseCount)).append("\n");
    sb.append("    passedTestCaseCount: ").append(toIndentedString(passedTestCaseCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
