/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.qatlas.client.model.TestStepAttachment;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * TestStep
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-02T18:40:14.833+02:00[Europe/Berlin]")
public class TestStep {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("testCaseId")
  private Long testCaseId = null;

  @JsonProperty("testCaseName")
  private String testCaseName = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("objectName")
  private String objectName = null;

  @JsonProperty("operation")
  private String operation = null;

  @JsonProperty("result")
  private String result = null;

  @JsonProperty("executionTime")
  private Long executionTime = null;

  /**
   * Gets or Sets executionStatus
   */
  public enum ExecutionStatusEnum {
    PLANNED("PLANNED"),
    PROGRESS("PROGRESS"),
    PASSED("PASSED"),
    FAILED("FAILED"),
    WARNING("WARNING");

    private String value;

    ExecutionStatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ExecutionStatusEnum fromValue(String text) {
      for (ExecutionStatusEnum b : ExecutionStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("executionStatus")
  private ExecutionStatusEnum executionStatus = null;

  @JsonProperty("attachments")
  private List<TestStepAttachment> attachments = null;

  public TestStep id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestStep testCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
    return this;
  }

   /**
   * Get testCaseId
   * @return testCaseId
  **/
  @Schema(required = true, description = "")
  public Long getTestCaseId() {
    return testCaseId;
  }

  public void setTestCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
  }

   /**
   * Get testCaseName
   * @return testCaseName
  **/
  @Schema(description = "")
  public String getTestCaseName() {
    return testCaseName;
  }

  public TestStep description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TestStep objectName(String objectName) {
    this.objectName = objectName;
    return this;
  }

   /**
   * Get objectName
   * @return objectName
  **/
  @Schema(description = "")
  public String getObjectName() {
    return objectName;
  }

  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }

  public TestStep operation(String operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @Schema(description = "")
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public TestStep result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(description = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public TestStep executionTime(Long executionTime) {
    this.executionTime = executionTime;
    return this;
  }

   /**
   * Get executionTime
   * @return executionTime
  **/
  @Schema(description = "")
  public Long getExecutionTime() {
    return executionTime;
  }

  public void setExecutionTime(Long executionTime) {
    this.executionTime = executionTime;
  }

  public TestStep executionStatus(ExecutionStatusEnum executionStatus) {
    this.executionStatus = executionStatus;
    return this;
  }

   /**
   * Get executionStatus
   * @return executionStatus
  **/
  @Schema(required = true, description = "")
  public ExecutionStatusEnum getExecutionStatus() {
    return executionStatus;
  }

  public void setExecutionStatus(ExecutionStatusEnum executionStatus) {
    this.executionStatus = executionStatus;
  }

  public TestStep attachments(List<TestStepAttachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public TestStep addAttachmentsItem(TestStepAttachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @Schema(description = "")
  public List<TestStepAttachment> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<TestStepAttachment> attachments) {
    this.attachments = attachments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestStep testStep = (TestStep) o;
    return Objects.equals(this.id, testStep.id) &&
        Objects.equals(this.testCaseId, testStep.testCaseId) &&
        Objects.equals(this.testCaseName, testStep.testCaseName) &&
        Objects.equals(this.description, testStep.description) &&
        Objects.equals(this.objectName, testStep.objectName) &&
        Objects.equals(this.operation, testStep.operation) &&
        Objects.equals(this.result, testStep.result) &&
        Objects.equals(this.executionTime, testStep.executionTime) &&
        Objects.equals(this.executionStatus, testStep.executionStatus) &&
        Objects.equals(this.attachments, testStep.attachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, testCaseId, testCaseName, description, objectName, operation, result, executionTime, executionStatus, attachments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestStep {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    testCaseId: ").append(toIndentedString(testCaseId)).append("\n");
    sb.append("    testCaseName: ").append(toIndentedString(testCaseName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    executionTime: ").append(toIndentedString(executionTime)).append("\n");
    sb.append("    executionStatus: ").append(toIndentedString(executionStatus)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
