/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.qatlas.client.model.AttachmentType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TestStepAttachment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-02T18:40:14.833+02:00[Europe/Berlin]")
public class TestStepAttachment {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("testStepId")
  private Long testStepId = null;

  @JsonProperty("attachmentType")
  private AttachmentType attachmentType = null;

  @JsonProperty("fileName")
  private String fileName = null;

  @JsonProperty("fileContent")
  private byte[] fileContent = null;

  @JsonProperty("fileContentBase64Encoded")
  private Boolean fileContentBase64Encoded = null;

  @JsonProperty("attachmentRelativePath")
  private String attachmentRelativePath = null;

  public TestStepAttachment id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestStepAttachment testStepId(Long testStepId) {
    this.testStepId = testStepId;
    return this;
  }

   /**
   * Get testStepId
   * @return testStepId
  **/
  @Schema(description = "")
  public Long getTestStepId() {
    return testStepId;
  }

  public void setTestStepId(Long testStepId) {
    this.testStepId = testStepId;
  }

  public TestStepAttachment attachmentType(AttachmentType attachmentType) {
    this.attachmentType = attachmentType;
    return this;
  }

   /**
   * Get attachmentType
   * @return attachmentType
  **/
  @Schema(required = true, description = "")
  public AttachmentType getAttachmentType() {
    return attachmentType;
  }

  public void setAttachmentType(AttachmentType attachmentType) {
    this.attachmentType = attachmentType;
  }

  public TestStepAttachment fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @Schema(required = true, description = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public TestStepAttachment fileContent(byte[] fileContent) {
    this.fileContent = fileContent;
    return this;
  }

   /**
   * Get fileContent
   * @return fileContent
  **/
  @Schema(required = true, description = "")
  public byte[] getFileContent() {
    return fileContent;
  }

  public void setFileContent(byte[] fileContent) {
    this.fileContent = fileContent;
  }

  public TestStepAttachment fileContentBase64Encoded(Boolean fileContentBase64Encoded) {
    this.fileContentBase64Encoded = fileContentBase64Encoded;
    return this;
  }

   /**
   * Get fileContentBase64Encoded
   * @return fileContentBase64Encoded
  **/
  @Schema(description = "")
  public Boolean isFileContentBase64Encoded() {
    return fileContentBase64Encoded;
  }

  public void setFileContentBase64Encoded(Boolean fileContentBase64Encoded) {
    this.fileContentBase64Encoded = fileContentBase64Encoded;
  }

   /**
   * Get attachmentRelativePath
   * @return attachmentRelativePath
  **/
  @Schema(description = "")
  public String getAttachmentRelativePath() {
    return attachmentRelativePath;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestStepAttachment testStepAttachment = (TestStepAttachment) o;
    return Objects.equals(this.id, testStepAttachment.id) &&
        Objects.equals(this.testStepId, testStepAttachment.testStepId) &&
        Objects.equals(this.attachmentType, testStepAttachment.attachmentType) &&
        Objects.equals(this.fileName, testStepAttachment.fileName) &&
        Arrays.equals(this.fileContent, testStepAttachment.fileContent) &&
        Objects.equals(this.fileContentBase64Encoded, testStepAttachment.fileContentBase64Encoded) &&
        Objects.equals(this.attachmentRelativePath, testStepAttachment.attachmentRelativePath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, testStepId, attachmentType, fileName, Arrays.hashCode(fileContent), fileContentBase64Encoded, attachmentRelativePath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestStepAttachment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    testStepId: ").append(toIndentedString(testStepId)).append("\n");
    sb.append("    attachmentType: ").append(toIndentedString(attachmentType)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileContent: ").append(toIndentedString(fileContent)).append("\n");
    sb.append("    fileContentBase64Encoded: ").append(toIndentedString(fileContentBase64Encoded)).append("\n");
    sb.append("    attachmentRelativePath: ").append(toIndentedString(attachmentRelativePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
