/*
 * testreports Backend
 * Test Automation Reporting Tool
 *
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.qatlas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.qatlas.client.model.ExecutionStatus;
import org.qatlas.client.model.TestExecution;
import org.qatlas.client.model.TestStep;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * TestCase
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-02T18:40:14.833+02:00[Europe/Berlin]")
public class TestCase {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("testSuiteId")
  private Long testSuiteId = null;

  @JsonProperty("testSuiteName")
  private String testSuiteName = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("referenceId")
  private String referenceId = null;

  @JsonProperty("executionStatus")
  private ExecutionStatus executionStatus = null;

  @JsonProperty("executionStartTime")
  private LocalDateTime executionStartTime = null;

  @JsonProperty("executionEndTime")
  private LocalDateTime executionEndTime = null;

  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("testSteps")
  private List<TestStep> testSteps = null;

  @JsonProperty("testExecution")
  private TestExecution testExecution = null;

  @JsonProperty("executionTime")
  private Long executionTime = null;

  @JsonProperty("testStepCountWithWarnings")
  private Integer testStepCountWithWarnings = null;

  @JsonProperty("totalTestStepCount")
  private Integer totalTestStepCount = null;

  @JsonProperty("failedTestStepCount")
  private Integer failedTestStepCount = null;

  @JsonProperty("executedTestStepCount")
  private Integer executedTestStepCount = null;

  @JsonProperty("passedTestStepCount")
  private Integer passedTestStepCount = null;

  public TestCase id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestCase testSuiteId(Long testSuiteId) {
    this.testSuiteId = testSuiteId;
    return this;
  }

   /**
   * Get testSuiteId
   * @return testSuiteId
  **/
  @Schema(required = true, description = "")
  public Long getTestSuiteId() {
    return testSuiteId;
  }

  public void setTestSuiteId(Long testSuiteId) {
    this.testSuiteId = testSuiteId;
  }

   /**
   * Get testSuiteName
   * @return testSuiteName
  **/
  @Schema(description = "")
  public String getTestSuiteName() {
    return testSuiteName;
  }

  public TestCase name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestCase referenceId(String referenceId) {
    this.referenceId = referenceId;
    return this;
  }

   /**
   * Get referenceId
   * @return referenceId
  **/
  @Schema(description = "")
  public String getReferenceId() {
    return referenceId;
  }

  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }

  public TestCase executionStatus(ExecutionStatus executionStatus) {
    this.executionStatus = executionStatus;
    return this;
  }

   /**
   * Get executionStatus
   * @return executionStatus
  **/
  @Schema(required = true, description = "")
  public ExecutionStatus getExecutionStatus() {
    return executionStatus;
  }

  public void setExecutionStatus(ExecutionStatus executionStatus) {
    this.executionStatus = executionStatus;
  }

  public TestCase executionStartTime(LocalDateTime executionStartTime) {
    this.executionStartTime = executionStartTime;
    return this;
  }

   /**
   * Get executionStartTime
   * @return executionStartTime
  **/
  @Schema(required = true, description = "")
  public LocalDateTime getExecutionStartTime() {
    return executionStartTime;
  }

  public void setExecutionStartTime(LocalDateTime executionStartTime) {
    this.executionStartTime = executionStartTime;
  }

  public TestCase executionEndTime(LocalDateTime executionEndTime) {
    this.executionEndTime = executionEndTime;
    return this;
  }

   /**
   * Get executionEndTime
   * @return executionEndTime
  **/
  @Schema(description = "")
  public LocalDateTime getExecutionEndTime() {
    return executionEndTime;
  }

  public void setExecutionEndTime(LocalDateTime executionEndTime) {
    this.executionEndTime = executionEndTime;
  }

  public TestCase comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

   /**
   * Get testSteps
   * @return testSteps
  **/
  @Schema(description = "")
  public List<TestStep> getTestSteps() {
    return testSteps;
  }

  public TestCase testExecution(TestExecution testExecution) {
    this.testExecution = testExecution;
    return this;
  }

   /**
   * Get testExecution
   * @return testExecution
  **/
  @Schema(description = "")
  public TestExecution getTestExecution() {
    return testExecution;
  }

  public void setTestExecution(TestExecution testExecution) {
    this.testExecution = testExecution;
  }

   /**
   * Get executionTime
   * @return executionTime
  **/
  @Schema(description = "")
  public Long getExecutionTime() {
    return executionTime;
  }

   /**
   * Get testStepCountWithWarnings
   * @return testStepCountWithWarnings
  **/
  @Schema(description = "")
  public Integer getTestStepCountWithWarnings() {
    return testStepCountWithWarnings;
  }

   /**
   * Get totalTestStepCount
   * @return totalTestStepCount
  **/
  @Schema(description = "")
  public Integer getTotalTestStepCount() {
    return totalTestStepCount;
  }

   /**
   * Get failedTestStepCount
   * @return failedTestStepCount
  **/
  @Schema(description = "")
  public Integer getFailedTestStepCount() {
    return failedTestStepCount;
  }

   /**
   * Get executedTestStepCount
   * @return executedTestStepCount
  **/
  @Schema(description = "")
  public Integer getExecutedTestStepCount() {
    return executedTestStepCount;
  }

   /**
   * Get passedTestStepCount
   * @return passedTestStepCount
  **/
  @Schema(description = "")
  public Integer getPassedTestStepCount() {
    return passedTestStepCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestCase testCase = (TestCase) o;
    return Objects.equals(this.id, testCase.id) &&
        Objects.equals(this.testSuiteId, testCase.testSuiteId) &&
        Objects.equals(this.testSuiteName, testCase.testSuiteName) &&
        Objects.equals(this.name, testCase.name) &&
        Objects.equals(this.referenceId, testCase.referenceId) &&
        Objects.equals(this.executionStatus, testCase.executionStatus) &&
        Objects.equals(this.executionStartTime, testCase.executionStartTime) &&
        Objects.equals(this.executionEndTime, testCase.executionEndTime) &&
        Objects.equals(this.comments, testCase.comments) &&
        Objects.equals(this.testSteps, testCase.testSteps) &&
        Objects.equals(this.testExecution, testCase.testExecution) &&
        Objects.equals(this.executionTime, testCase.executionTime) &&
        Objects.equals(this.testStepCountWithWarnings, testCase.testStepCountWithWarnings) &&
        Objects.equals(this.totalTestStepCount, testCase.totalTestStepCount) &&
        Objects.equals(this.failedTestStepCount, testCase.failedTestStepCount) &&
        Objects.equals(this.executedTestStepCount, testCase.executedTestStepCount) &&
        Objects.equals(this.passedTestStepCount, testCase.passedTestStepCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, testSuiteId, testSuiteName, name, referenceId, executionStatus, executionStartTime, executionEndTime, comments, testSteps, testExecution, executionTime, testStepCountWithWarnings, totalTestStepCount, failedTestStepCount, executedTestStepCount, passedTestStepCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestCase {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    testSuiteId: ").append(toIndentedString(testSuiteId)).append("\n");
    sb.append("    testSuiteName: ").append(toIndentedString(testSuiteName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("    executionStatus: ").append(toIndentedString(executionStatus)).append("\n");
    sb.append("    executionStartTime: ").append(toIndentedString(executionStartTime)).append("\n");
    sb.append("    executionEndTime: ").append(toIndentedString(executionEndTime)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    testSteps: ").append(toIndentedString(testSteps)).append("\n");
    sb.append("    testExecution: ").append(toIndentedString(testExecution)).append("\n");
    sb.append("    executionTime: ").append(toIndentedString(executionTime)).append("\n");
    sb.append("    testStepCountWithWarnings: ").append(toIndentedString(testStepCountWithWarnings)).append("\n");
    sb.append("    totalTestStepCount: ").append(toIndentedString(totalTestStepCount)).append("\n");
    sb.append("    failedTestStepCount: ").append(toIndentedString(failedTestStepCount)).append("\n");
    sb.append("    executedTestStepCount: ").append(toIndentedString(executedTestStepCount)).append("\n");
    sb.append("    passedTestStepCount: ").append(toIndentedString(passedTestStepCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
